version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo ${POSTGRES_URL}
      - "docker build 
      --build-arg APP_DB_URL=${POSTGRES_URL} 
      --build-arg APP_DB_USER=${POSTGRES_USER} 
      --build-arg APP_DB_PASSWORD=${POSTGRES_PASS} 
      --build-arg APP_S3_BUCKET=${APP_S3_BUCKET} 
      --build-arg APP_S3_KEY=${APP_S3_KEY} 
      --build-arg AWS_ACCESS_KEY_ID=${ACCESS_ID} 
      --build-arg AWS_SECRET_ACCESS_KEY=${ACCESS_KEY} 
       -t $IMAGE_REPO_NAME:$IMAGE_TAG ."
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG