services:
  db:
    image: postgres:15.5
    environment:
      POSTGRES_PASSWORD: donttellnoone
      POSTGRES_DB: commerce-store
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
